// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgfnznsvscgvlcizcfzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnZm56bnN2c2NndmxjaXpjZnp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODc3MTcsImV4cCI6MjA2MzY2MzcxN30.g_dSLmzpYhF4veh9W1bIHbYMD1kdlKHCj11ad77QDHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);